spring:
  datasource:
    url: jdbc:sqlserver://mfpservermain.database.windows.net:1433;database=mfpuserDb;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: mfp
    password: passer@123

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
      dialect: org.hibernate.dialect.SQLServerDialect

  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    port: 587
    username: alyndiaye.ag@gmail.com
    password: hxpx nseb cygj mybt
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


server:
  port: 9191


  #spring.mail.default-encoding=UTF-8
  #spring.mail.host=smtp.gmail.com
  #spring.mail.port=587
  #spring.mail.username=alyndiaye.ag@gmail.com
  #spring.mail.password=hxpx nseb cygj mybt
  #spring.mail.properties.mail.smtp.auth=true
  #spring.mail.properties.mail.smtp.starttls.enable=true
